project_id = "ycsisvozzgmisboumfqc"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ycsisvozzgmisboumfqc.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[edge_runtime]
enabled = true
port = 54329

[functions.ai-fleet-analyst]
verify_jwt = false

[functions.voice-command-center]
verify_jwt = false

[functions.intelligent-alerts]
verify_jwt = false

[functions.smart-reporting]
verify_jwt = false

[functions.predictive-maintenance]
verify_jwt = false

[functions.ottocommand-ai-chat]
verify_jwt = false

[functions.ottoq-vehicles-telemetry]
verify_jwt = false

[functions.ottoq-jobs-request]
verify_jwt = false

[functions.ottoq-depots-resources]
verify_jwt = false

[functions.ottoq-vehicles-status]
verify_jwt = false

[functions.ottoq-jobs-cancel]
verify_jwt = false

[functions.ottoq-schedules-upsert]
verify_jwt = false

[functions.ottoq-config]
verify_jwt = false

[functions.ottoq-scheduler]
verify_jwt = false

[functions.ottoq-simulator]
verify_jwt = false

[functions.update-vehicle-oems]
verify_jwt = false
