name: Claude Code

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened]

# Grant the action the rights it needs
permissions:
  id-token: write          # for OIDC
  contents: write          # to push branches
  pull-requests: write     # to open/update PRs
  issues: write            # <-- needed to POST comments
  actions: read

jobs:
  run-claude:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ github.token }}   # <-- use github.token, not secrets.GITHUB_TOKEN
